local expand_line_begin = require("luasnip.extras.conditions.expand").line_begin
local tex = require("math-snippets.latex")
local pos = require("math-snippets.position")

local reference_prefixes = { a = "auto", r = "", z = "zc" }

local text_opts = { condition = tex.in_text, show_condition = tex.in_text }
local line_begin_opts = { condition = expand_line_begin * tex.in_text, show_condition = pos.show_line_begin * tex.in_text }

local function phrase_snippet(trig, body)
	return s({ trig = trig, desc = trig }, t(body), text_opts)
end

local function rational_phrase_snippet(trig, name)
	return s({ trig = trig, name = name, trigEngine = "pattern" }, {
		f(function (_, snip)
			return "\\(\\mathbb{" .. snip.captures[1]:upper() .. "}\\)-" .. name
		end, {})
	}, text_opts)
end

local snips = {
	s({ trig = "cf", name = "cross reference" }, fmta([[\cite[<>]{<>}<>]], { i(1), i(2), i(0) }), text_opts)
}

local autosnips = {
	s({
		trig = "alab",
		name = "label",
		desc = "add a label"
	}, fmta([[\zlabel{<>:<>}<>]], { i(1), i(2), i(0) })),

	s({
		trig = "([arz])ref",
		name = "(arz)?ref",
		desc = "add a reference (with autoref, zcref)",
		trigEngine = "pattern",
		hidden = true
	},
		fmta([[\<>ref{<>}<>]], {
			f(function (_, snip)
				return reference_prefixes[snip.captures[1]]
			end),
			i(1),
			i(0)
		}), text_opts),

	s({ trig = "eqref", desc = "add a reference with eqref", hidden = true }, fmta([[\eqref{eq:<>}<>]], { i(1), i(0) }), {
		condition = tex.in_text,
		show_condition = tex.in_text,
		callbacks = {
			[1] = {
				[events.enter] = function ()
					local ok, blink = pcall(require, "blink.cmp")
					if ok then
						blink.show({ providers = { "lsp" } })
					end
				end
			}
		}
	}),

	s({
		trig = "Tfae",
		name = "The following are equivalent"
	}, { t("The following are equivalent") }, line_begin_opts),

	s({
		trig = "([wW])log",
		name = "without loss of generality",
		trigEngine = "pattern"
	},
		{
			f(function (_, snip)
				return snip.captures[1] .. "ithout loss of generality"
			end, {})
		}, line_begin_opts),

	rational_phrase_snippet("([qr])c", "Cartier"),
	rational_phrase_snippet("([qr])d", "divisor")
}

local phrase_specs = {
	klt = "Kawamata log terminal",
	resp = "resp.\\ ",
	ses = "short exact sequence"
}

local auto_phrase_specs = {
	bqf = "base point free",
	cd = "Cartier divisor",
	egg = "e.g., ",
	fgd = "finitely generated",
	gbgs = "generated by global sections",
	ggg = "generically globally generated",
	iee = "i.e., ",
	iff = "if and only if ",
	lci = "local complete intersection",
	lmm = "log minimal model",
	mfs = "Mori fibre space",
	nbhd = "neighbourhood",
	nc = "\\((-1)\\)-curve",
	pef = "pseudo-effective",
	qf = "\\(\\mathbb{Q}\\)-factorial",
	snc = "simple normal crossing",
	stt = "such that",
	tfae = "the following are equivalent",
	wd = "Weil divisor",
	wrt = "with respect to "
}

for k, v in pairs(phrase_specs) do
	table.insert(snips, phrase_snippet(k, v))
end
for k, v in pairs(auto_phrase_specs) do
	table.insert(autosnips, phrase_snippet(k, v))
end

return snips, autosnips
